name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish new release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qbench
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel
      - name: Clean previous builds
        run: |
          rm -rf dist/ build/ *.egg-info/
      - name: Build package
        run: |
          python -m build  # This is the modern recommended way
      - name: Check built packages
        run: |
          ls -la dist/
          python -c "import qbench; print(f'Version: {qbench.__version__}')"
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1